### ISSUE TITLE
Missing CHANGELOG.md	

### ISSUE THREAD

**Issue by derdanu** [neptunel/AzureOpenSourceRepoTemplate#1]
CHANGELOG.md is referred in the README.md table but the template file itself is missing.

**Comment by neptunel** [comment]
CHANGELOG.md is a part of the sample templates, we don't need to use the exact table of contents. Checkout these 3 samples about how you might change it based on your own repo structure: 
https://github.com/Azure/AzReplicate
https://github.com/Azure/AzBulkSetBlobTier 
https://github.com/azure/azdatamaker/tree/master/
I'll remove CHANGELOG.md from the table to prevent confusion. THX!
